src/Entity/Header.php
<?php

namespace App\Entity;

use App\Repository\HeaderRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HeaderRepository::class)]
class Header
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $btnTitle = null;

    #[ORM\Column(length: 255)]
    private ?string $btnURL = null;

    #[ORM\Column(length: 255)]
    private ?string $Illustration = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getBtnTitle(): ?string
    {
        return $this->btnTitle;
    }

    public function setBtnTitle(string $btnTitle): self
    {
        $this->btnTitle = $btnTitle;

        return $this;
    }

    public function getBtnURL(): ?string
    {
        return $this->btnURL;
    }

    public function setBtnURL(string $btnURL): self
    {
        $this->btnURL = $btnURL;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->Illustration;
    }

    public function setIllustration(string $Illustration): self
    {
        $this->Illustration = $Illustration;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Classe\Cart;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    
    private $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * Récapitulatif panier
    */

    #[Route('/mon-panier', name: 'app_cart')]

    public function index(Cart $cart): Response
    {
        // code avant création de contion getFull();
        // // Panier complet
        // $cartComplete = [];

        // if($cart->get()){

            
        //     // Enrichir le cartComplete de datas pris par Doctrine en BDD
        //     // as $id(clé) => $qunatity(valeur)
        //     foreach ($cart->get() as $id => $quantity) {
        //         // a chaque itération, injete dans $cartComplete[] une nouvelle entrée avec plusieurs parametres
        //         $cartComplete[] = [
        //             // produit venant de la BDD via Doctrine et EntityManager intialisé par __construct, recherche du produit par $id produit
        //             'product' => $this->entityManager->getRepository(Product::class)->findOneById($id), 
        //             'quantity' => $quantity
        //         ];
        //     }
        // }

        return $this->render('cart/index.html.twig', [
        // on insert dans la vue le tableau $cart->get() du panier avec le couple id.produit + quantity
            //'cart' => $cart->get()

            // passer à la vue le tableau généré dans $cartComplete
            'cart' => $cart->getFull()
        ]);
    }
    
    
    
    /**
     * Ajout au panier
     * @param $id
    */

    #[Route('/cart/add/{id}', name: 'add_to_cart')]


    public function add(Cart $cart, $id)  
    {
        $cart->add($id);

        return $this->redirectToRoute('app_cart');
    }

    
    /**
     * Vider le panier
    */

    #[Route('/cart/remove', name: 'remove_my_cart')]


    public function remove(Cart $cart)  
    {
        
        $cart->remove();
        
        return $this->redirectToRoute('app_products');

    }

    /**
     * retirer une sorte d'article du panier
    */

    #[Route('/cart/delete/{id}', name: 'delete_to_cart')]


    public function delete(Cart $cart, $id)  
    {
        
        $cart->delete($id);
        
        return $this->redirectToRoute('app_cart');

    }

    /**
     * retirer une quantité d'article du panier
    */

    #[Route('/cart/decrease/{id}', name: 'decrease_to_cart')]


    public function decrease(Cart $cart, $id)  
    {
        
        $cart->decrease($id);
        
        return $this->redirectToRoute('app_cart');

    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier | La Boutique Française!
{% endblock %}

{% block content %}

	<h1>Mon Panier</h1>
	retrouver tous les articles ajoutés dans votre panier

	{% if cart|length > 0 %}


		<div class="example-wrapper">


			<table class="table mt-4">

				<thead>
					<tr>
						<th scope="col">Produit</th>
						<th scope="col"></th>
						<th scope="col">Quantity</th>
						<th scope="col">Prix</th>
						<th scope="col">Total</th>
						<th scope="col"></th>
					</tr>
				</thead>

				<tbody class="table-group-divider">
					{% set total = null %}
					{% set nbProducts = 0 %}
					{% for product in cart %}

						<tr>
							<th>
								<img src="/uploads/{{ product.product.illustration }}" alt="{{ product.product.name }}" height="100px">
							</th>
							<th scope="row">{{ product.product.name }}<br>
								<small>{{ product.product.subtitle }}</small>
							</th>
							<td>
							<a href="{{ path('decrease_to_cart', { 'id' : product.product.id }) }}"> 
								<img src="{{ asset('assets/img/minus.png') }}" alt="Diminuer la quantité" width="17px" class="mx-2">
							</a>
									{{ product.quantity }}
							<a href=" {{ path('add_to_cart', { 'id' : product.product.id }) }} "> {# Fonction add() #}
								<img src="{{ asset('assets/img/add.png') }}" alt="Augmenter la quantité" height="17px" class="mx-2">
							</a>
							</td>
							<td>{{ (product.product.price / 100)|number_format(2, ',','.') }} €</td>
							<td>
								<strong>
									{{ ((product.product.price * product.quantity ) / 100)|number_format(2, ',','.') }} €
								</strong>
							</td>
							<td>
								<a href=" {{ path('delete_to_cart', { 'id' : product.product.id }) }} ">
									<img src="{{ asset('assets/img/delete.png') }}" alt="Supprimer mon produit" height="25px">
								</a>
							</td>
						</tr>
						{% set total = total + (product.product.price * product.quantity ) %}
						{% set nbProducts = nbProducts + (product.quantity) %}
					{% endfor %}

				</tbody>

			</table>
		</div>
		<div class="text-right">
			{# <b>Nombre d'articles : {{ cart|length }} </b> <br> Affichage du nombre de sorte de produits #}
			<b>Nombre d'articles :
				{{ nbProducts }}
				{# constante nombre de produits #}
			</b>
			<br>
			<b>Total de mon panier :
				{{ (total / 100)|number_format(2, ',','.') }}€
			</b>
			<a href="{{ path('app_order') }}" class="btn btn-success btn-block mt-3 fw-bold">
				<strong>Valider mon panier</strong>
			</a>
		</div>
		<a href=" {{ path('app_products') }} " class="btn btn-info btn-block mt-5"><b>Continuez vos achats</b></a>

        {% else %}
            <hr>
            <p class="fw-bold"><b>Votre panier est vide</b></p><br>
            <a href=" {{ path('app_products') }} ">Nos produits</a>
        {% endif %}

	{% endblock %}